# 服务器配置
server:
  port: 80
  servlet:
    context-path: /

# Spring配置
spring:
  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

    # 德鲁伊配置
    druid:
      url: jdbc:mysql://localhost:3306/1024.glod?serverTimezone=UTC
      username: root
      password: Hhn004460
      initial-size: 5
      min-idle: 5
      max-active: 100
      max-wait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      # filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  # 配置RabbitMQ
  rabbitmq:
    host: 192.168.154.128
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  # 关闭thymeleaf缓存
  thymeleaf:
    cache: false


# 日志配置
logging:
  file:
    path: /system/log
    name: system.log
  pattern:
    console: "%d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n"
  level:
    root: info

mybatis:
  configuration:
    map-underscore-to-camel-case: true
